/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservarRouteImport } from './routes/reservar'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as IndexRouteImport } from './routes/index'

const ReservarRoute = ReservarRouteImport.update({
  id: '/reservar',
  path: '/reservar',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/productos': typeof ProductosRoute
  '/reservar': typeof ReservarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/productos': typeof ProductosRoute
  '/reservar': typeof ReservarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contacto': typeof ContactoRoute
  '/nosotros': typeof NosotrosRoute
  '/productos': typeof ProductosRoute
  '/reservar': typeof ReservarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/contacto' | '/nosotros' | '/productos' | '/reservar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/contacto' | '/nosotros' | '/productos' | '/reservar'
  id: '__root__' | '/' | '/contacto' | '/nosotros' | '/productos' | '/reservar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactoRoute: typeof ContactoRoute
  NosotrosRoute: typeof NosotrosRoute
  ProductosRoute: typeof ProductosRoute
  ReservarRoute: typeof ReservarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservar': {
      id: '/reservar'
      path: '/reservar'
      fullPath: '/reservar'
      preLoaderRoute: typeof ReservarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactoRoute: ContactoRoute,
  NosotrosRoute: NosotrosRoute,
  ProductosRoute: ProductosRoute,
  ReservarRoute: ReservarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
